import { constants } from "node:fs";
import { access, lstat, mkdir, open, readFile, realpath, unlink } from "node:fs/promises";
import path from "node:path";
import { sha256 } from "@/lib/crypto";

const idPattern=/^[A-Za-z0-9_-]{1,128}$/;const hashPattern=/^[a-f0-9]{64}$/;
export function artifactRelativePath(tenantId:string,fortigateId:string,digest:string,file="configuration.conf"){if(!idPattern.test(tenantId)||!idPattern.test(fortigateId)||!hashPattern.test(digest)||!/^configuration(?:\.analysis(?:\.[A-Za-z0-9_-]{1,128})?)?\.(?:conf|pdf)$/.test(file))throw new Error("INVALID_ARTIFACT_ID");return path.join("data","backups",tenantId,fortigateId,digest,file);}
export function artifactAbsolutePath(relative:string){const root=path.resolve(process.cwd(),"data","backups");const normalized=relative.replace(/\\/g,"/");const prefix="data/backups/";if(!normalized.startsWith(prefix))throw new Error("INVALID_ARTIFACT_PATH");const absolute=path.resolve(process.cwd(),"data","backups",normalized.slice(prefix.length));const rel=path.relative(root,absolute);if(!rel||rel.startsWith("..")||path.isAbsolute(rel))throw new Error("INVALID_ARTIFACT_PATH");return absolute;}
export async function writeImmutableArtifact(relative:string,content:Buffer){const absolute=artifactAbsolutePath(relative);await mkdir(path.dirname(absolute),{recursive:true,mode:0o700});try{const handle=await open(absolute,"wx",0o600);try{await handle.writeFile(content);await handle.sync();}finally{await handle.close();}const directory=await open(path.dirname(absolute),"r");try{await directory.sync();}catch{}finally{await directory.close();}}catch(error){if(!(error&&typeof error==="object"&&"code" in error&&error.code==="EEXIST"))throw error;const existing=await readFile(absolute);if(sha256(existing)!==sha256(content))throw new Error("ARTIFACT_COLLISION");}await verifyImmutableArtifact(relative,sha256(content),content.byteLength);return absolute;}
export async function verifyImmutableArtifact(relative:string,digest:string,size:number){const absolute=artifactAbsolutePath(relative);const info=await lstat(absolute);if(info.isSymbolicLink()||!info.isFile()||info.size!==size)throw new Error("ARTIFACT_INTEGRITY_FAILED");const resolved=await realpath(absolute);const root=await realpath(path.resolve(process.cwd(),"data","backups"));if(!resolved.startsWith(root+path.sep))throw new Error("ARTIFACT_OUTSIDE_ROOT");await access(absolute,constants.R_OK);const content=await readFile(absolute);if(sha256(content)!==digest)throw new Error("ARTIFACT_INTEGRITY_FAILED");return content;}
export async function removeVerifiedReportArtifact(relative:string,digest:string,size:number){if(!/[/\\]configuration\.analysis(?:\.[A-Za-z0-9_-]{1,128})?\.pdf$/.test(relative))throw new Error("INVALID_REPORT_PATH");await verifyImmutableArtifact(relative,digest,size);const absolute=artifactAbsolutePath(relative);await unlink(absolute);const directory=await open(path.dirname(absolute),"r");try{await directory.sync();}catch{}finally{await directory.close();}}
