import { z } from "zod";
import { residualSecretScan, safeFoundryPayloadSchema, type SafeFoundryPayload } from "./safe-foundry";

const outputSchema=z.object({managementSummary:z.string().min(1).max(2000),enhancements:z.array(z.object({ruleId:z.string().regex(/^FG-[A-Z]+-\d{3}$/),context:z.string().max(800),remediation:z.string().max(1200)}).strict()).max(500)}).strict();
export type FoundryEnrichment=z.infer<typeof outputSchema> & {requestId:string|null;durationMs:number};
const HOSTS=[/^[a-z0-9-]+\.openai\.azure\.com$/i,/^[a-z0-9-]+\.services\.ai\.azure\.com$/i];
export function validateFoundryEndpoint(source:string){const url=new URL(source);if(url.protocol!=="https:"||url.username||url.password||url.port||!HOSTS.some((p)=>p.test(url.hostname)))throw new Error("INVALID_FOUNDRY_ENDPOINT");const pathname=url.pathname.replace(/\/+$/,"");if(pathname!==""&&!/^\/api\/projects\/[A-Za-z0-9._-]+$/.test(pathname))throw new Error("INVALID_FOUNDRY_ENDPOINT");url.pathname=pathname||"/";return url;}
export function validateDeployment(value:string){if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value))throw new Error("INVALID_FOUNDRY_DEPLOYMENT");return value;}

export async function enrichWithFoundry(config:{endpoint:string;deployment:string;apiKey:string},payload:SafeFoundryPayload,transport:typeof fetch=fetch):Promise<FoundryEnrichment>{
  safeFoundryPayloadSchema.parse(payload);residualSecretScan(payload);const endpoint=validateFoundryEndpoint(config.endpoint);const deployment=validateDeployment(config.deployment);const body=JSON.stringify({model:deployment,store:false,tools:[],input:[{role:"system",content:[{type:"input_text",text:"Geef uitsluitend JSON met managementSummary en enhancements. Baseer je alleen op de gestructureerde technische bevindingen. Geef geen CLI-opdrachten."}]},{role:"user",content:[{type:"input_text",text:JSON.stringify(payload)}]}],text:{format:{type:"json_schema",name:"fortibackup_analysis",strict:true,schema:{type:"object",additionalProperties:false,required:["managementSummary","enhancements"],properties:{managementSummary:{type:"string",maxLength:2000},enhancements:{type:"array",maxItems:500,items:{type:"object",additionalProperties:false,required:["ruleId","context","remediation"],properties:{ruleId:{type:"string"},context:{type:"string",maxLength:800},remediation:{type:"string",maxLength:1200}}}}}}}}});
  if(Buffer.byteLength(body)>300_000)throw new Error("FOUNDRY_REQUEST_TOO_LARGE");
  const started=Date.now();let last:Error|null=null;
  for(let attempt=0;attempt<3;attempt+=1){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30_000);try{const basePath=endpoint.pathname.replace(/\/+$/,"");const response=await transport(new URL(`${basePath}/openai/v1/responses`,endpoint.origin),{method:"POST",redirect:"error",headers:{"content-type":"application/json","accept":"application/json","api-key":config.apiKey},body,signal:controller.signal});if(response.status===401||response.status===403)throw new Error("FOUNDRY_AUTH_INVALID");if((response.status===429||response.status>=500)&&attempt<2){const retry=Math.min(Number(response.headers.get("retry-after")??1)*1000,10_000);await new Promise((resolve)=>setTimeout(resolve,retry));continue;}if(!response.ok)throw new Error(`FOUNDRY_HTTP_${response.status}`);const raw=await readBounded(response,512_000);const outputText=extractOutputText(JSON.parse(raw));residualSecretScanResponse(outputText);const value=outputSchema.parse(JSON.parse(outputText));return{...value,requestId:response.headers.get("x-request-id")??response.headers.get("apim-request-id"),durationMs:Date.now()-started};}catch(error){last=error instanceof Error?error:new Error("FOUNDRY_FAILED");if(["FOUNDRY_AUTH_INVALID","SENSITIVE_DATA_DETECTED"].includes(last.message))throw last;}finally{clearTimeout(timer);}}
  throw last??new Error("FOUNDRY_FAILED");
}
async function readBounded(response:Response,max:number){const reader=response.body?.getReader();if(!reader)return "";let size=0;const chunks:Uint8Array[]=[];for(;;){const{done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new Error("FOUNDRY_RESPONSE_TOO_LARGE");}chunks.push(value);}return new TextDecoder().decode(Buffer.concat(chunks));}
function residualSecretScanResponse(value:string){if(/<[^>]+>|-----BEGIN|\b(?:password|psk|secret|token|api[-_ ]?key)\b|\b[A-Za-z0-9+/]{96,}={0,2}\b/i.test(value))throw new Error("SENSITIVE_DATA_DETECTED");}

function extractOutputText(value:unknown){const envelope=z.object({output:z.array(z.object({content:z.array(z.object({type:z.string(),text:z.string().max(256_000)}).passthrough()).max(20)}).passthrough()).max(20)}).passthrough().parse(value);const text=envelope.output.flatMap((item)=>item.content).filter((item)=>item.type==='output_text').map((item)=>item.text).join('');if(!text)throw new Error('FOUNDRY_OUTPUT_INVALID');return text;}
