import { readFile } from "node:fs/promises";
import path from "node:path";
import PDFDocument from "pdfkit";
import SVGtoPDF from "svg-to-pdfkit";
import { artifactRelativePath, writeImmutableArtifact } from "./artifact-storage";
import type { LocalFinding } from "./rules";

type ReportInput={reportId:string;tenantId:string;tenantName:string;customerName:string;fortigateId:string;hostname:string;model:string;fortiOsVersion:string;configDate:Date;analysisDate:Date;score:number;scoreDelta:number|null;passedControls:number;totalControls:number;hash:string;parserVersion:string;rulesetVersion:string;summary:string;findings:LocalFinding[];newFindingIds:string[];resolvedFindingIds:string[]};
export async function generateSecurityReport(input:ReportInput){const chunks:Buffer[]=[];const doc=new PDFDocument({size:"A4",margins:{top:72,bottom:64,left:50,right:50},info:{Title:`FortiBackup beveiligingsanalyse ${input.hostname}`,Author:"FortiBackup",Subject:"Immutable FortiGate-configuratieanalyse"},bufferPages:true,autoFirstPage:false});doc.on("data",(chunk)=>chunks.push(chunk));const complete=new Promise<Buffer>((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);});const addPage=async()=>{doc.addPage();doc.rect(0,0,595,54).fill("#11243e");try{const logo=await readFile(path.join(process.cwd(),"public","brand","forti-backup-logo-dark.svg"),"utf8");SVGtoPDF(doc,logo,50,14,{width:142,height:28});}catch{doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(17).text("FortiBackup",50,18);}doc.fillColor("#617087").font("Helvetica").fontSize(8).text("VERTROUWELIJK - IMMUTABLE RAPPORT",50,570,{width:495,align:"center"});doc.y=72;};await addPage();doc.fillColor("#11243e").font("Helvetica-Bold").fontSize(24).text("FortiGate beveiligingsanalyse",50,90);doc.font("Helvetica").fontSize(10).fillColor("#617087").text(`${input.customerName} - ${input.hostname}`,50,124);doc.roundedRect(50,158,180,112,8).fill("#edf7f4");doc.fillColor(scoreColor(input.score)).font("Helvetica-Bold").fontSize(48).text(`${input.score}%`,70,180,{width:140,align:"center"});doc.fillColor("#11243e").fontSize(10).text("TECHNISCHE SCORE",70,238,{width:140,align:"center"});doc.fillColor("#11243e").font("Helvetica-Bold").fontSize(14).text("Managementsamenvatting",260,164);doc.font("Helvetica").fontSize(10).fillColor("#334155").text(sanitize(input.summary),260,190,{width:285,lineGap:3});doc.moveDown(2);section(doc,"Rapportgegevens");const rows=[["Tenant",input.tenantName],["FortiGate",`${input.hostname} (${input.model})`],["FortiOS",input.fortiOsVersion],["Configuratiedatum",iso(input.configDate)],["Analysedatum",iso(input.analysisDate)],["Geslaagde controles",`${input.passedControls} van ${input.totalControls}`],["Scoreberekening","Gewogen geslaagde punten / gewogen toepasselijke punten"],["Scoreverschil",input.scoreDelta===null?"Geen eerdere analyse":`${input.scoreDelta>=0?"+":""}${input.scoreDelta} procentpunt`],["Configuratiehash",input.hash],["Parser / ruleset",`${input.parserVersion} / ${input.rulesetVersion}`],["Rapport-ID",input.reportId]];for(const [label,value] of rows){await ensure(doc,28,addPage);doc.font("Helvetica-Bold").fontSize(9).fillColor("#617087").text(label,50,doc.y,{width:125});doc.font("Helvetica").fillColor("#11243e").text(value,180,doc.y-10,{width:365});doc.moveDown(.75);}
section(doc,"Wijzigingen ten opzichte van de vorige configuratie");doc.font("Helvetica").fontSize(10).fillColor("#334155").text(`Nieuwe bevindingen: ${input.newFindingIds.length?input.newFindingIds.join(", "):"geen"}`);doc.text(`Opgeloste bevindingen: ${input.resolvedFindingIds.length?input.resolvedFindingIds.join(", "):"geen"}`);section(doc,"Bevindingen");for(const finding of [...input.findings].sort((a,b)=>rank(a.severity)-rank(b.severity))){await ensure(doc,118,addPage);const y=doc.y;doc.roundedRect(50,y,495,104,5).fillAndStroke("#f8fafc","#d9e1ea");doc.fillColor(severityColor(finding.severity)).font("Helvetica-Bold").fontSize(9).text(finding.severity,64,y+12,{width:70});doc.fillColor("#11243e").fontSize(11).text(`${finding.ruleId} - ${sanitize(finding.title)}`,135,y+11,{width:392});doc.font("Helvetica").fontSize(9).fillColor("#334155").text(sanitize(finding.explanation),64,y+34,{width:467,height:28,ellipsis:true});doc.font("Helvetica-Bold").fillColor("#617087").text("Bewijs",64,y+65);doc.font("Helvetica").fillColor("#334155").text(sanitize(finding.evidence),110,y+65,{width:421,height:16,ellipsis:true});doc.font("Helvetica-Bold").fillColor("#617087").text("Advies",64,y+83);doc.font("Helvetica").fillColor("#334155").text(sanitize(finding.remediation),110,y+83,{width:421,height:16,ellipsis:true});doc.y=y+116;}const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(range.start+i);doc.font("Helvetica").fontSize(8).fillColor("#617087").text(`Pagina ${i+1} van ${range.count}`,475,570,{width:70,align:"right"});}doc.end();const buffer=await complete;const relative=artifactRelativePath(input.tenantId,input.fortigateId,input.hash,"configuration.analysis.pdf");await writeImmutableArtifact(relative,buffer);return{relative,buffer};}
function section(doc:PDFKit.PDFDocument,title:string){doc.moveDown(1.5);doc.fillColor("#11243e").font("Helvetica-Bold").fontSize(14).text(title);doc.moveDown(.6);}
function ensure(doc:PDFKit.PDFDocument,height:number,addPage:()=>Promise<void>){if(doc.y+height>555)return addPage();return Promise.resolve();}
function sanitize(value:string){return value.replace(/<[^>]*>/g,"").replace(/[\u0000-\u001f\u007f]/g," ").slice(0,4000);}
function iso(value:Date){return new Intl.DateTimeFormat("nl-NL",{dateStyle:"long",timeStyle:"short",timeZone:"UTC"}).format(value)+" UTC";}
function rank(value:string){return ["CRITICAL","HIGH","MEDIUM","LOW"].indexOf(value);}
function scoreColor(score:number){return score>=80?"#08775a":score>=60?"#b56a00":"#b42318";}
function severityColor(value:string){return value==="CRITICAL"?"#8f1522":value==="HIGH"?"#b42318":value==="MEDIUM"?"#b56a00":"#2d63a3";}
