import { createHash, randomUUID } from "node:crypto";
import { copyFile, lstat, mkdir, open, readFile, realpath, rename, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { backup as sqliteBackup, DatabaseSync } from "node:sqlite";
import pg from "pg";
import { convertLegacyValue } from "./legacy-value-conversion";

const {Client}=pg;const APP=process.cwd();const DATA=path.join(APP,"data");const STATUS=path.join(DATA,"postgres-migration-state.json");
class Database extends DatabaseSync {
  constructor(file:string,options?:unknown){void options;super(file,{readOnly:true});}
  pragma(statement:string,options?:{simple?:boolean}){const rows=this.prepare(`PRAGMA ${statement}`).all() as Array<Record<string,unknown>>;return options?.simple?Object.values(rows[0]??{})[0]:rows;}
  backup(target:string){return sqliteBackup(this,target);}
}
const phases=["PREFLIGHT","SNAPSHOTTED","PG_PROVISIONED","SCHEMA_CREATED","DATA_COPIED","FILES_COPIED","VERIFIED","CUTOVER","HEALTH_VERIFIED","COMPLETE"] as const;type Phase=typeof phases[number];
type State={migrationVersion:1;installationId:string;sourceRelease:string;sourceCommit:string;sourcePath:string;sourceSha256:string;sourceSize:number;postgresDatabaseId:string;phase:Phase;startedAt:string;updatedAt:string;recoveryPath:string};
const legacyTables=["Tenant","User","AccessPermission","AccessRole","AccessRolePermission","UserAccessRole","Account","Session","VerificationToken","SetupToken","LoginThrottle","Customer","FortiGate","BackupJob","Backup","FortiGateLog","VersionHistory","AuditLog","SystemSetting"];
const supportedMigrations=["20260616162000_init","20260623145000_fortigate_logs","20260623162000_tls_verify_default_false","20260624105000_fortigate_summary_inventory","20260624160000_itglue_integration","20260701143000_user_must_change_password","20260701152000_tenant_rbac","20260702120000_session_active_tenant","20260707140000_autotask_backup_tickets","20260707150000_break_glass_settings_session","20260713120000_security_hardening","20260721100000_fortigate_certificate_pinning"];

main().catch((error)=>{process.stderr.write(`SQLite naar PostgreSQL migratie mislukt: ${safeError(error)}\n`);process.exitCode=1;});
async function main(){const sourceUrl=process.env.DATABASE_URL??"";if(!sourceUrl.startsWith("file:"))throw new Error("DATABASE_URL_IS_NOT_LEGACY_SQLITE");const targetUrl=process.env.POSTGRES_MIGRATION_URL??"";if(!/^postgres(?:ql)?:/.test(targetUrl))throw new Error("POSTGRES_MIGRATION_URL_REQUIRED");const runtimeTargetUrl=process.env.POSTGRES_RUNTIME_URL??"";if(!/^postgres(?:ql)?:/.test(runtimeTargetUrl))throw new Error("POSTGRES_RUNTIME_URL_REQUIRED");const source=resolveSqlite(sourceUrl);const installationId=await installationIdentity();const sourceInfo=await stat(source);const sourceHash=await digestFile(source);let state=await readState();if(state&&(state.installationId!==installationId||state.sourceSha256!==sourceHash||state.sourceSize!==sourceInfo.size))throw new Error("MIGRATION_STATE_SOURCE_MISMATCH");const client=new Client({connectionString:targetUrl,application_name:"fortibackup-legacy-migrator"});await client.connect();try{const dbId=await databaseIdentity(client);if(state&&state.postgresDatabaseId!==dbId)throw new Error("MIGRATION_STATE_TARGET_MISMATCH");if(!state){await preflight(source);const recovery=path.join(DATA,"recovery",`sqlite-postgres-${new Date().toISOString().replace(/[:.]/g,"-")}`);await mkdir(recovery,{recursive:true,mode:0o700});state={migrationVersion:1,installationId,sourceRelease:process.env.npm_package_version??"unknown",sourceCommit:await gitCommit(),sourcePath:source,sourceSha256:sourceHash,sourceSize:sourceInfo.size,postgresDatabaseId:dbId,phase:"PREFLIGHT",startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),recoveryPath:recovery};await writeState(state);await copySecure(path.join(APP,".env"),path.join(recovery,"legacy.env"));}
  const snapshot=path.join(state.recoveryPath,"legacy.sqlite");if(before(state,"SNAPSHOTTED")){const db=new Database(source,{readonly:true,fileMustExist:true});try{await db.backup(snapshot);}finally{db.close();}await verifySqlite(snapshot);await writeManifest(snapshot,state.recoveryPath);state=await advance(state,"SNAPSHOTTED");}
  if(before(state,"PG_PROVISIONED"))state=await advance(state,"PG_PROVISIONED");
  if(before(state,"SCHEMA_CREATED")){await assertBaselinePresent(client);await assertTargetEmpty(client);state=await advance(state,"SCHEMA_CREATED");}
  if(before(state,"DATA_COPIED")){await importData(snapshot,client);state=await advance(state,"DATA_COPIED");}
  if(before(state,"FILES_COPIED")){await importArtifacts(snapshot,client);state=await advance(state,"FILES_COPIED");}
  if(before(state,"VERIFIED")){await verifyImport(snapshot,client);state=await advance(state,"VERIFIED");}
  if(before(state,"CUTOVER")){await atomicCutover(runtimeTargetUrl);state=await advance(state,"CUTOVER");}
  process.stdout.write(`Conversie gevalideerd en cutover uitgevoerd. Status: ${state.phase}. Voer nu applicatie-healthchecks uit.\n`);
}finally{await client.end();}}
function resolveSqlite(url:string){const value=url.slice(5);const result=path.resolve(APP,"prisma",value);return result;}
async function preflight(source:string){const info=await lstat(source);if(!info.isFile()||info.isSymbolicLink())throw new Error("SQLITE_SOURCE_INVALID");await verifySqlite(source);const free=await import("node:fs/promises").then((fs)=>fs.statfs(DATA));if(Number(free.bavail)*Number(free.bsize)<info.size*3+256*1024*1024)throw new Error("INSUFFICIENT_DISK_SPACE");}
async function verifySqlite(file:string){const db=new Database(file,{readonly:true,fileMustExist:true});try{const integrity=db.pragma("integrity_check",{simple:true});if(integrity!=="ok")throw new Error("SQLITE_INTEGRITY_CHECK_FAILED");const foreign=db.pragma("foreign_key_check") as unknown[];if(foreign.length)throw new Error("SQLITE_FOREIGN_KEY_CHECK_FAILED");const applied=db.prepare("SELECT migration_name FROM _prisma_migrations WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL ORDER BY started_at").all().map((row:Record<string,unknown>)=>String(row.migration_name));if(!applied.length||applied.some((name,index)=>supportedMigrations[index]!==name))throw new Error("UNSUPPORTED_SQLITE_MIGRATION_HISTORY");const globalCount=(db.prepare("SELECT count(*) count FROM Tenant WHERE kind='GLOBAL'").get() as {count:number}).count;if(globalCount>1)throw new Error("DUPLICATE_GLOBAL_TENANT");const duplicate=db.prepare('SELECT key FROM SystemSetting WHERE tenantId IS NULL GROUP BY key HAVING count(*)>1 LIMIT 1').get();if(duplicate)throw new Error("DUPLICATE_GLOBAL_SETTING");const badEnums=db.prepare("SELECT id FROM Tenant WHERE kind NOT IN ('GLOBAL','CUSTOMER') LIMIT 1").get();if(badEnums)throw new Error("INVALID_ENUM_VALUE");await validateLegacyConfigFiles(db);}finally{db.close();}}
async function assertBaselinePresent(client:pg.Client){const exists=await client.query("SELECT to_regclass('\"Tenant\"') name");if(!exists.rows[0]?.name)throw new Error("POSTGRES_BASELINE_MISSING");}
async function assertTargetEmpty(client:pg.Client){for(const table of legacyTables){const result=await client.query(`SELECT count(*)::int count FROM ${quote(table)}`);if(result.rows[0].count!==0)throw new Error(`POSTGRES_TARGET_NOT_EMPTY_${table}`);}}
async function importData(snapshot:string,client:pg.Client){const db=new Database(snapshot,{readonly:true});try{await client.query("BEGIN");await client.query("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");for(const table of legacyTables){const sourceColumns=(db.prepare(`PRAGMA table_info(${quoteSqlite(table)})`).all() as Array<{name:string}>).map((x)=>x.name);const target=(await client.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position",[table])).rows as Array<{column_name:string;data_type:string}>;const targetNames=new Set(target.map((x)=>x.column_name));const columns=sourceColumns.filter((name)=>targetNames.has(name));if(table==="Backup"&&!columns.includes("tenantId"))columns.push("tenantId");const rows=db.prepare(`SELECT * FROM ${quoteSqlite(table)} ORDER BY rowid`).all() as Record<string,unknown>[];for(const row of rows){if(table==="Backup")row.tenantId=(db.prepare('SELECT c.tenantId FROM FortiGate f JOIN Customer c ON c.id=f.customerId WHERE f.id=?').get(String(row.fortigateId)) as {tenantId:string})?.tenantId;if(table==="AuditLog"&&row.integrityHash){/* preserved byte-for-byte; AuditHead is rebuilt below */}const values=columns.map((column)=>convertLegacyValue(row[column],target.find((x)=>x.column_name===column)?.data_type,`${table}.${column}`));const params=values.map((_,i)=>`$${i+1}`).join(",");await client.query(`INSERT INTO ${quote(table)} (${columns.map(quote).join(",")}) VALUES (${params})`,values);}}
  const auditHeads=await client.query('SELECT DISTINCT "tenantId" FROM "AuditLog"');for(const {tenantId} of auditHeads.rows){const last=await client.query('SELECT id,"integrityHash" FROM "AuditLog" WHERE "tenantId" IS NOT DISTINCT FROM $1 ORDER BY "createdAt" DESC,id DESC LIMIT 1',[tenantId]);const scope=tenantId?`tenant:${tenantId}`:"global";await client.query('INSERT INTO "AuditHead" ("scopeKey","tenantId","lastAuditId","lastHash","updatedAt") VALUES ($1,$2,$3,$4,now())',[scope,tenantId,last.rows[0]?.id??null,last.rows[0]?.integrityHash??null]);}await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{db.close();}}
async function importArtifacts(snapshot:string,client:pg.Client){const db=new Database(snapshot,{readonly:true});try{const rows=db.prepare("SELECT b.id,b.filename,b.sha256,b.filesize,b.createdAt,f.id fortigateId,c.tenantId FROM Backup b JOIN FortiGate f ON f.id=b.fortigateId JOIN Customer c ON c.id=f.customerId WHERE b.status='CHANGED' AND b.filename IS NOT NULL ORDER BY b.createdAt").all() as Array<{id:string;filename:string;sha256:string;filesize:number;createdAt:string|number|Date;fortigateId:string;tenantId:string}>;for(const row of rows){if(!/^[a-f0-9]{64}$/.test(row.sha256))throw new Error("INVALID_CONFIG_HASH");const source=path.resolve(APP,String(row.filename));const root=await realpath(path.join(APP,"data","backups"));const sourceInfo=await lstat(source);if(sourceInfo.isSymbolicLink()||!sourceInfo.isFile()||!(await realpath(source)).startsWith(root+path.sep))throw new Error("CONFIG_PATH_INVALID");if(sourceInfo.size!==row.filesize||await digestFile(source)!==row.sha256)throw new Error("CONFIG_INTEGRITY_MISMATCH");const relative=path.join("data","backups",row.tenantId,row.fortigateId,row.sha256,"configuration.conf");const target=path.join(APP,relative);await mkdir(path.dirname(target),{recursive:true,mode:0o700});try{await copyExclusive(source,target);}catch(error){if(safeError(error)!=="EEXIST"||await digestFile(target)!==row.sha256)throw error;}if(await digestFile(target)!==row.sha256)throw new Error("CONFIG_COPY_MISMATCH");const artifactId=`legacy_${row.id}`;await client.query('INSERT INTO "ConfigArtifact" (id,"tenantId","fortigateId",sha256,path,filesize,"createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT ("tenantId","fortigateId",sha256) DO NOTHING',[artifactId,row.tenantId,row.fortigateId,row.sha256,relative.replace(/\\/g,"/"),row.filesize,new Date(row.createdAt)]);const artifact=await client.query('SELECT id FROM "ConfigArtifact" WHERE "tenantId"=$1 AND "fortigateId"=$2 AND sha256=$3',[row.tenantId,row.fortigateId,row.sha256]);await client.query('UPDATE "Backup" SET "configArtifactId"=$1,filename=$2 WHERE id=$3',[artifact.rows[0].id,relative.replace(/\\/g,"/"),row.id]);}}finally{db.close();}}
async function verifyImport(snapshot:string,client:pg.Client){const db=new Database(snapshot,{readonly:true});try{for(const table of legacyTables){const source=(db.prepare(`SELECT count(*) count FROM ${quoteSqlite(table)}`).get() as {count:number}).count;const target=Number((await client.query(`SELECT count(*) count FROM ${quote(table)}`)).rows[0].count);if(source!==target)throw new Error(`ROW_COUNT_MISMATCH_${table}`);const primary=(db.prepare(`PRAGMA table_info(${quoteSqlite(table)})`).all() as Array<{name:string;pk:number}>).filter((x)=>x.pk>0).sort((a,b)=>a.pk-b.pk).map((x)=>x.name);if(primary.length){const order=primary.map(quote).join(",");const sourceKeys=db.prepare(`SELECT ${order} FROM ${quoteSqlite(table)} ORDER BY ${order}`).all();const targetKeys=(await client.query(`SELECT ${order} FROM ${quote(table)} ORDER BY ${order}`)).rows;if(hashJson(sourceKeys)!==hashJson(targetKeys))throw new Error(`PRIMARY_KEY_DIGEST_MISMATCH_${table}`);}}const fk=await client.query("SELECT conname FROM pg_constraint WHERE contype='f' AND NOT convalidated");if(fk.rowCount)throw new Error("POSTGRES_FOREIGN_KEYS_NOT_VALIDATED");}finally{db.close();}}
async function atomicCutover(runtimeTargetUrl:string){const envPath=path.join(APP,".env");const input=await readFile(envPath,"utf8");const lines=input.split(/\r?\n/).filter(Boolean);const updated=lines.map((line)=>line.startsWith("DATABASE_URL=")?`DATABASE_URL=${JSON.stringify(runtimeTargetUrl)}`:line);if(!updated.some((line)=>line.startsWith("NEXT_TELEMETRY_DISABLED=")))updated.push("NEXT_TELEMETRY_DISABLED=1");if(!updated.some((line)=>line.startsWith("CHECKPOINT_DISABLE=")))updated.push("CHECKPOINT_DISABLE=1");const temporary=`${envPath}.postgres.tmp`;const handle=await open(temporary,"wx",0o600);try{await handle.writeFile(updated.join("\n")+"\n");await handle.sync();}finally{await handle.close();}await rename(temporary,envPath);}
async function installationIdentity(){const file=path.join(DATA,"installation-id");try{return (await readFile(file,"utf8")).trim();}catch{const id=randomUUID();await writeFile(file,id+"\n",{flag:"wx",mode:0o600});return id;}}
async function databaseIdentity(client:pg.Client){const row=(await client.query("SELECT oid::text,datname FROM pg_database WHERE datname=current_database()")).rows[0];return `${row.oid}:${row.datname}`;}
async function readState(){try{return JSON.parse(await readFile(STATUS,"utf8")) as State;}catch{return null;}}
async function writeState(state:State){await mkdir(path.dirname(STATUS),{recursive:true});const temp=`${STATUS}.${process.pid}.tmp`;const handle=await open(temp,"wx",0o600);try{await handle.writeFile(JSON.stringify(state,null,2)+"\n");await handle.sync();}finally{await handle.close();}await rename(temp,STATUS);}
async function advance(state:State,phase:Phase){const next={...state,phase,updatedAt:new Date().toISOString()};await writeState(next);return next;}
function before(state:State,phase:Phase){return phases.indexOf(state.phase)<phases.indexOf(phase);}
async function copySecure(source:string,target:string){await copyFile(source,target);const handle=await open(target,"r+");try{await handle.chmod(0o600);await handle.sync();}finally{await handle.close();}}
async function copyExclusive(source:string,target:string){const input=await open(source,"r");const output=await open(target,"wx",0o600);try{const content=await input.readFile();await output.writeFile(content);await output.sync();}finally{await input.close();await output.close();}}
async function writeManifest(snapshot:string,recovery:string){const db=new Database(snapshot,{readonly:true});let configurations:unknown[];try{configurations=db.prepare("SELECT id,filename,sha256,filesize FROM Backup WHERE status='CHANGED' AND filename IS NOT NULL ORDER BY id").all();}finally{db.close();}const manifest={snapshotSha256:await digestFile(snapshot),snapshotSize:(await stat(snapshot)).size,createdAt:new Date().toISOString(),configurations};await writeFile(path.join(recovery,"manifest.json"),JSON.stringify(manifest,null,2)+"\n",{flag:"wx",mode:0o600});}
async function digestFile(file:string){const hash=createHash("sha256");const handle=await open(file,"r");try{for await(const chunk of handle.readableWebStream())hash.update(Buffer.from(chunk));return hash.digest("hex");}finally{await handle.close();}}
function hashJson(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
function quote(value:string){return `"${value.replace(/"/g,'""')}"`;}
function quoteSqlite(value:string){return quote(value);}
function safeError(error:unknown){if(error&&typeof error==="object"&&"code" in error)return String(error.code);return error instanceof Error?error.message:"UNKNOWN_ERROR";}
async function gitCommit(){return process.env.FORTIBACKUP_SOURCE_COMMIT??"unknown";}
async function validateLegacyConfigFiles(db:Database){const root=await realpath(path.join(APP,"data","backups"));const rows=db.prepare("SELECT id,filename,sha256,filesize FROM Backup WHERE status='CHANGED' AND filename IS NOT NULL").all() as Array<{id:string;filename:string;sha256:string;filesize:number}>;for(const row of rows){const file=path.resolve(APP,String(row.filename));const info=await lstat(file);const resolved=await realpath(file);if(info.isSymbolicLink()||!info.isFile()||!resolved.startsWith(root+path.sep))throw new Error("CONFIG_PATH_INVALID");if(!/^[a-f0-9]{64}$/.test(String(row.sha256))||info.size!==row.filesize||await digestFile(file)!==row.sha256)throw new Error("CONFIG_INTEGRITY_MISMATCH");}}
