import { notFound } from "next/navigation";
import { ActionLink, Badge, Card, PageHeader, Shell, TableShell } from "@/components/ui";
import { assertTenantAccess, requirePermission } from "@/lib/authz";
import { prisma } from "@/lib/db";
import { fortigateScoreHistory } from "@/lib/security/queries";

export const dynamic="force-dynamic";
export default async function FortigateSecurityPage({params}:{params:Promise<{id:string;fortigateId:string}>}){const user=await requirePermission("security.analyses.read");const {id,fortigateId}=await params;const device=await prisma.fortiGate.findFirst({where:{id:fortigateId,customerId:id},include:{customer:true}});if(!device)notFound();assertTenantAccess(user,device.customer.tenantId);const history=await fortigateScoreHistory(device.customer.tenantId,device.id);const points=history.flatMap((backup)=>backup.configArtifact?.analysis?.score===null||backup.configArtifact?.analysis?.score===undefined?[]:[{backupId:backup.id,date:backup.createdAt,hash:backup.sha256??"",...backup.configArtifact.analysis}]);const latest=points.at(-1);return <Shell><PageHeader title={`Scorehistorie - ${device.hostname??"FortiGate"}`} description="Alleen gewijzigde configuratiemomenten met een voltooide immutable analyse." actions={<ActionLink href={`/customers/${id}/fortigates/${fortigateId}`}>Terug naar FortiGate</ActionLink>}/><div className="grid gap-4 sm:grid-cols-3"><Card title="Actuele score" value={latest?.score===undefined?"Niet geanalyseerd":`${latest.score}%`}/><Card title="Meetpunten" value={points.length}/><Card title="Laatste analyse" value={latest?.completedAt?.toLocaleDateString("nl-NL")??"-"}/></div><section className="mt-6 rounded-xl border border-border bg-surface p-5 shadow-panel"><h2 className="font-display text-xl font-semibold">Historische score</h2>{points.length?<ScoreChart points={points.map((p)=>({score:p.score!,label:p.date.toLocaleDateString("nl-NL")}))}/>:<p className="mt-4 text-muted-foreground">Nog geen voltooide analyses.</p>}</section><TableShell className="mt-6"><table className="table-pro w-full min-w-[900px] text-left text-sm"><thead><tr><th>Configuratiedatum</th><th>Score</th><th>Verschil</th><th>Critical / high / medium / low</th><th>Hash</th><th>Versies</th><th>Actie</th></tr></thead><tbody>{points.map((point,index)=>{const previous=points[index-1];return <tr key={point.backupId} className="border-t border-border"><td>{point.date.toLocaleString("nl-NL")}</td><td><Badge tone={point.score!>=80?"success":point.score!>=60?"warning":"danger"}>{point.score}%</Badge></td><td>{previous?`${point.score!-previous.score!>=0?"+":""}${point.score!-previous.score!} procentpunt`:"-"}</td><td>{point.criticalCount} / {point.highCount} / {point.mediumCount} / {point.lowCount}</td><td className="font-mono">{point.hash.slice(0,12)}</td><td>{point.parserVersion} / {point.rulesetVersion}</td><td><ActionLink href={`/security/analyses/${point.id}`}>Open analyse</ActionLink></td></tr>})}</tbody></table></TableShell></Shell>}
function ScoreChart({points}:{points:Array<{score:number;label:string}>}){const width=900,height=240,pad=35;const coords=points.map((p,i)=>({x:points.length===1?width/2:pad+i*(width-2*pad)/(points.length-1),y:pad+(100-p.score)*(height-2*pad)/100,...p}));return <div className="mt-4 overflow-x-auto"><svg role="img" aria-label="FortiGate scorehistorie in procenten" viewBox={`0 0 ${width} ${height}`} className="min-w-[700px]"><path d={`M ${coords.map((p)=>`${p.x} ${p.y}`).join(" L ")}`} fill="none" stroke="hsl(var(--primary))" strokeWidth="3"/>{[0,25,50,75,100].map((score)=><g key={score}><line x1={pad} x2={width-pad} y1={pad+(100-score)*(height-2*pad)/100} y2={pad+(100-score)*(height-2*pad)/100} stroke="hsl(var(--border))"/><text x="2" y={pad+(100-score)*(height-2*pad)/100+4} fontSize="11" fill="currentColor">{score}%</text></g>)}{coords.map((p)=><g key={`${p.x}-${p.label}`}><circle cx={p.x} cy={p.y} r="6" fill="hsl(var(--primary))"><title>{p.label}: {p.score}%</title></circle></g>)}</svg></div>}
